### ISSUE TITLE
A little question about the rtisqp_export

### ISSUE THREAD

**Issue by chentairan** [larsvens/tamp_ws#1]
Hey @larsvens  Thanks for making this great work for Traction Adaptive Motion Planning. It's really helpful and I'd like to use and cite it in my research.

One little question, Is rtisqp_export generated by acado? I don't seem to see the code generation file of MATLAB or cpp.

Best,
Tairan Chen

**Comment by larsvens** [comment]
Hi there Tairan, thank you for your message. I'm glad the framework can be of use to you.

Regarding your question, yes rtisqp_export is generated by acado, and deployed into the saarti workspace. I had this question before, so I shall make it a priority to make this more clear in the readme. Let me know if there's anything else I can assist you with. 

Best,
Lars

**Comment by chentairan** [comment]
Hi,
About the RTI solver, where is the code of code generation, and how do I generate the C code.
Best,
Tairan Chen

**Comment by larsvens** [comment]
In my fork of the acado repo: https://github.com/larsvens/acado_fork . Follow those instructions to deploy the RTI solver in the tamp workspace. I realized that this information was missing in the readme. Have updated now. Thanks for the feedback.

**Comment by chentairan** [comment]
Thank you very much, I will try it.

**Comment by larsvens** [comment]
Great, let me know if there are any other issues :)

**Comment by chentairan** [comment]
There is a little suggestion, maybe providing a non-GPU compilation option in CMakelists and code is better 🤔

**Comment by larsvens** [comment]
Yes that's on my todo-list. Will be added soon. The sampling augmentation really benefits from GPU acceleration though, and I really recommend running it on GPU if possible.

**Comment by chentairan** [comment]
I see👌🏻

**Comment by chentairan** [comment]
Hi Lars,

Do you know how to set an objective function with a negative weight in Acado, such as -w * v, where -w is the weight and v is the speed of the vehicle, this objective function is to make the speed as fast as possible

Best,
Tairan

**Comment by larsvens** [comment]
Hi Tairan,
The term in your cost function is actually w(v_ref-v), so just setting a high reference velocity should achieve what you are looking for. 

Best,
Lars

**Comment by chentairan** [comment]
Wow, great idea, thanks !
